<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type="text/xsl" href="lyraxsl.xsl"?>
<!DOCTYPE lyra[
  <!ELEMENT lyra (Song*)>
  <!ELEMENT Song (Number,Title,Text,Translations) >
  <!ELEMENT Translations (Translation*)>
  <!ELEMENT Translation (Title,Text)>
  <!ELEMENT Number (#PCDATA)>
  <!ELEMENT Title (#PCDATA)>
  <!ELEMENT Text (#PCDATA)>
  <!ATTLIST Song id ID #REQUIRED>]>
<lyra>
  <Song id="s0001">
    <Number>1</Number>
    <Title>Jubilate Deo</Title>
    <Text>Jubilate Deo, jubilate Deo. Alleluja!   (Jubelt Gott zu, Halleluja!)
</Text>
    <Translations>
      <Translation>
        <Title>O let the Son of God</Title>
        <Text>O let the Son of God enfold you with His spirit and His love,
let Him fill your heart and satisfy your soul.
O let Him have the things that hold you, and His spirit like a dove
will descend upon your life and make you whole.

Jesus, o Jesus, come and fill Your lambs.	(2x)

O come and sing this song with gladness as your hearts are filled with joy,
lift your hands in sweet surrender to His name.
O give Him all your tears and sadness, give Him all your years of pain,
and you'll enter into life in Jesus' name.
</Text>
      </Translation>
    </Translations>
  </Song>
  <Song id="s0002">
    <Number>2</Number>
    <Title>Gloria</Title>
    <Text>Gloria, gloria, gloria Patri et Filio.
Gloria, gloria, gloria Spiritui Sancto

Ehre sei dem Vater und dem Sohn.
Ehre sei dem Heiligen Geist.

</Text>
  </Song>
  <Song id="s0003">
    <Number>3</Number>
    <Title>Wir sind hier zusammen in Jesu Namen</Title>
    <Text>Wir sind hier zusammen in Jesu Namen, um dich zu loben, o Herr.	(2x)
Ehr sei dem Vater, Ehr sei dem Sohn, Ehr sei dem Heilgen Geist,
der in uns wohnt.	(2x)
Halleluja, halleluja, halleluja, halleluja!
</Text>
  </Song>
  <Song id="s0004">
    <Number>4</Number>
    <Title>Halleluja, singt dem Herrn ein neues Lied</Title>
    <Text>Halleluja, singt dem Herrn ein neues Lied. Wir loben dich, Herr.
Wir preisen deinen heiligen Namen, o Gott.
Heiliger Gott, komm in deiner Herrlichkeit und zieh bei uns ein:
Erfüll mit deiner Gegenwart diesen Ort.
Hör uns, o Gott, in Einheit loben wir dich. Wir beten dich an
und bringen dir, unserm Herrn, ein Lobopfer dar.
</Text>
  </Song>
  <Song id="s0005">
    <Number>5</Number>
    <Title>Komm in unsre Mitte, o Herr</Title>
    <Text>Komm in unsre Mitte, o Herr, o Herr, o Herr.				(2x)
	
Fülle uns mit deinem Heilgen Geist, o Herr, wir danken dir.		(2x)

Deine Gnade schenkst du täglich neu, o Herr, wir danken dir.	(2x)

Du bist in unsrer Mitte... 

Lass uns spüren, dass du bei uns bist, o Herr, wir danken dir.	(2x)

Bleib in unsrer Mitte... 

Lass uns hören, was du heut uns sagst, o Herr, wir danken dir.	(2x)

Bleib in unsrer Mitte...











</Text>
  </Song>
  <Song id="s0006">
    <Number>6</Number>
    <Title>Lass dich erfüllen</Title>
    <Text>O let the Son of God enfold you with His spirit and His love,
let Him fill your heart and satisfy your soul.
O let Him have the things that hold you, and His spirit like a dove
will descend upon your life and make you whole.

Jesus, o Jesus, come and fill Your lambs.	(2x)

O come and sing this song with gladness as your hearts are filled with joy,
lift your hands in sweet surrender to His name.
O give Him all your tears and sadness, give Him all your years of pain,
and you'll enter into life in Jesus' name.

Lass dich erfüllen von der Liebe; Jesus sendet seinen Geist.
Lass dich beschenken von der Gnade unsres Herrn.
O, gib ihm alles, was dich hindert, dass sein Geist dich fülle neu
und dein Leben heilig und ein Wohlklang sei!

Jesus, o Jesus, komm erfülle mich.	(2x)

O, gib der Freude Raum im Herzen und sing fröhlich dieses Lied!
Heb die Hände vor dem König und sag Dank.
O, gib ihm alle deine Tränen, gib ihm Sorgen, Angst und Not;
und Erfüllung find't dein Leben vor dem Herrn.









</Text>
  </Song>
  <Song id="s0007">
    <Number>7</Number>
    <Title>Wir versammeln uns zu dir</Title>
    <Text>Wir versammeln uns zu dir, o grosser Gott.   (2x)
Nur zu dir soll dein Volk sich sammeln, denn du bist gut.
Wir versammeln uns zu dir, o grosser Gott.
</Text>
  </Song>
  <Song id="s0008">
    <Number>8</Number>
    <Title>Lasst uns treten in sein Haus</Title>
    <Text>Lasst uns treten in sein Haus, versammeln uns zu ihm
und beten an   (3x)   den Herrn; beten an Christus, den Herrn.

Lasst nun alles andre stehn, und richtet euren Blick auf ihn
und betet an   (3x)   den Herrn; betet an Christus, den Herrn.

Hebet heilge Hände auf, verherrlicht seinen Nam
und betet an   (3x)   den Herrn; betet an Christus, den Herrn.
</Text>
  </Song>
  <Song id="s0009">
    <Number>9</Number>
    <Title>Kommt und lasst uns ziehn</Title>
    <Text>Kommt und lasst uns ziehn hinauf zum Berge unsres Herrn,
zum Hause Gottes lasst uns gehn.   (2x)
Und er wird uns seine Wahrheit lehr'n,
und wir werden seine Wege gehn,
und Weisung wird ausgehn von Zion
und das Wort unsres Herrn von Jerusalem.</Text>
  </Song>
  <Song id="s0010">
    <Number>10</Number>
    <Title>Das Wort Christi</Title>
    <Text>Das Wort Christi wohne mit seinem ganzen Reichtum,
mit seinem Reichtum bei euch, halleluja.
</Text>
  </Song>
  <Song id="s0011">
    <Number>11</Number>
    <Title>Vater, ich will dich preisen</Title>
    <Text>Vater, ich will dich preisen, denn dein Wort ist wunderbar.
Vater, ich will dich preisen, denn dein Wort ist wunderbar
und vollkommen.

Jeden Morgen staun ich neu, was dein Wort enthält.			(2x)
Ich erkenne, dein Wort hält stets, was es verspricht.			(2x)
Ja, in Zeit und Ewigkeit hat dein Wort Bestand.					(2x)
Freude, Kraft, Mut, Zuversicht, all das schenkt dein Wort.		(2x)
</Text>
  </Song>
  <Song id="s0012">
    <Number>12</Number>
    <Title>Thy word</Title>
    <Text>Thy word is a lamp unto my feet and a light unto my path.   (2x)

When I feel afraid, think I've lost my way, still You're there right beside me;
and nothing will I fear as long as You are near,
please be near me to the end.

I will not forget Your love for me and yet my heart forever is wandering;
Jesus be my guide, hold me to Your side, and I will love You to the end.

Dis Wort isch es Liecht uf mim Wäg, und es lüüchtet mine Füess. (2x)

Hätti nid dis Wort as mi Troscht i aller Not - i wüssti nid, was i täti!
S wiist de rächti Wäg, schänkt Erquickig jede Tag - Herr,
dis Wort isch wunderbar!

Jedes Wort isch wahr, s'bliibt beschtoh für immerdar; es lehrt mi dini Wäge.
Meh as Gold und Gäld, als alles i de Wält, liebi dini Wiisige.











</Text>
  </Song>
  <Song id="s0013">
    <Number>13</Number>
    <Title>Ein neuer Tag bricht an</Title>
    <Text>Ein neuer Tag bricht an, ein Tag des Glaubens,
ein neuer Tag bricht an, ein Tag des Sieges.
Drum singt ein neues Lied, drum singt ein neues Lied,
drum singt ein neues Lied vor dem Herrn.   (2x)
</Text>
  </Song>
  <Song id="s0014">
    <Number>14</Number>
    <Title>Erfülle dieses Land</Title>
    <Text>Erfülle dieses Land mit der Herrlichkeit des Herrn,
erfülle dieses Land mit der Herrlichkeit des Herrn,
die Erde sei voll mit der Herrlichkeit des Herrn,
die Erde sei voll mit der Herrlichkeit des Herrn.
</Text>
  </Song>
  <Song id="s0015">
    <Number>15</Number>
    <Title>Brecht in Jubel aus</Title>
    <Text>Brecht in Jubel aus und singt, verkündigt es unter den Völkern:
Der König der Ehre, der König der Ehre, der König der Ehre, er kommt!
</Text>
  </Song>
  <Song id="s0016">
    <Number>16</Number>
    <Title>Der Herr ist König, gepriesen</Title>
    <Text>Der Herr ist König, der Herr ist König, gepriesen sei der Name des Herrn!
Denn der Herr, unser Gott, der Allmächtige regiert in Majestät.
</Text>
  </Song>
  <Song id="s0017">
    <Number>17</Number>
    <Title>Ehre, Ehre, Ehre sei dem Lamm</Title>
    <Text>Ehre, Ehre, Ehre sei dem Lamm. Ehre, Ehre, Ehre sei dem Lamm.
Denn du bist würdig, Lobpreis zu empfangen, Lamm Gottes auf dem Thron,
und du wirst kommen, um die Erde zu richten in Gerechtigkeit.
</Text>
  </Song>
  <Song id="s0018">
    <Number>18</Number>
    <Title>Dein Reich komme</Title>
    <Text>Dein Reich komme; dein Wille geschehe!
Erneure meinen Sinn, dir zu gehorchen! Ich geb dir mein Leben hin.
Dein Reich komme!
</Text>
  </Song>
  <Song id="s0019">
    <Number>19</Number>
    <Title>O Herr, du Gott Israels</Title>
    <Text>O Herr, du Gott Israels, es ist kein Gott wie du in der Höh;
es ist kein Gott wie du auf der Erd, o Herr, du Gott Israels.
Du hältst deinen Bund und zeigst deine Gnade all deinen Knechten,
die vor dir wandeln mit ganzem Herzen.
O Herr, du Gott Israels, es ist kein Gott wie du in der Höh;
es ist kein Gott wie du auf der Erd, o Herr, du Gott Israels.
</Text>
  </Song>
  <Song id="s0020">
    <Number>20</Number>
    <Title>Höre, Israel</Title>
    <Text>Höre, Israel! Der Herr ist unser Gott, der Herr allein!   (2x)
Und du sollst den Herrn, deinen Gott, lieben von ganzem Herzen!
Und du sollst den Herrn, deinen Gott, lieben von ganzer Seele!
Und du sollst den Herrn, deinen Gott, lieben mit aller deiner Kraft!
</Text>
  </Song>
  <Song id="s0021">
    <Number>21</Number>
    <Title>Love the Lord your God</Title>
    <Text>Love the Lord your God with all your heart, and all your soul and all your
mind and love all of mankind as you would love yourself and   (Love!)   (2x)

Love the Lord your God with all your heart and all your soul and mind
and love all of mankind.   (Love!)   (2x)

We've got Christian lives to live, we've got Jesus' love to give,
we've got nothing to hide because in Him we abide.   (Love!)   (2x)
</Text>
  </Song>
  <Song id="s0022">
    <Number>22</Number>
    <Title>Der Gerechte ist stark wie ein Löwe</Title>
    <Text>Der Gerechte ist stark wie ein Löwe!
Der Gottlose flieht, auch wenn niemand ihn jagt.   (2x)
Denn der Herr ist mit dem Gerechten,
er ist sein Schild und sein Gesang.
Denn der Herr ist mit dem Gerechten,
er ist sein Schild und Gesang.
</Text>
  </Song>
  <Song id="s0023">
    <Number>23</Number>
    <Title>Der Herr ist der Starke und Mächtige</Title>
    <Text>Der Herr ist der Starke und Mächtige, der Herr der Held im Streit.
Der Herr ist der Starke und Mächtige, Herr Zebaoth ist er.

Ich bin stark in dem Herrn, denn der Allmächtige lebt in mir.
Ich bin stark in dem Herrn und rufe aus seinen Sieg.
</Text>
  </Song>
  <Song id="s0024">
    <Number>24</Number>
    <Title>Der Name des Herrn ist eine feste Burg</Title>
    <Text>Der Name des Herrn ist eine feste Burg;   (3x)
der Gerechte läuft dorthin und wird beschirmt.
Mächtig ist der Name Jesu:   (3x)
Er ist der starke Fels!
</Text>
  </Song>
  <Song id="s0025">
    <Number>25</Number>
    <Title>Vater, ich lieb dich</Title>
    <Text>Vater, ich lieb dich, ich preise und erhebe dich.
Herrlich sei dein Name in der Welt!
Herrlich sei dein Name, herrlich sei dein Name,
herrlich sei dein Name in der Welt!

Jesus, ich lieb dich ...

Heilger Geist, ich lieb dich ...
</Text>
  </Song>
  <Song id="s0026">
    <Number>26</Number>
    <Title>Preis dem Namen Jesus</Title>
    <Text>Preis dem Namen Jesus, Preis dem Namen Jesus;
er ist mein Fels, er ist meine Festung, er ist mein Erlöser,
auf ihn will ich vertraun. Preis dem Namen Jesus.
</Text>
  </Song>
  <Song id="s0027">
    <Number>27</Number>
    <Title>Name so wunderbar</Title>
    <Text>Name so wunderbar, Name so wunderbar,
Name so wunderbar: Jesus, mein Herr.
König der Welten, dein Wort soll gelten,
Name so wunderbar: Jesus, mein Herr.
Er will dich leiten, der Fels aller Zeiten, sein ist ja alle Macht.
O betet Jesus an; rühmt ihn, den Schmerzensmann,
Name so wunderbar: Jesus, mein Herr.
</Text>
  </Song>
  <Song id="s0028">
    <Number>28</Number>
    <Title>Ich bin entschieden</Title>
    <Text>Ich bin entschieden, zu folgen Jesus -				(3x)
niemals zurück, niemals zurück.

Ob niemand mit mir geht, doch will ich folgen -		(3x)
niemals zurück, niemals zurück.

Die Welt liegt hinter mir, das Kreuz steht vor mir -	(3x)
niemals zurück, niemals zurück.
</Text>
  </Song>
  <Song id="s0029">
    <Number>29</Number>
    <Title>Jesus will uns baun</Title>
    <Text>Jesus will uns baun zu einem Tempel, als Wohnung für den heilgen Gott.
Dies Haus des Herrn ist die Gemeinde, die Säule und der Wahrheit Grund.
Wie Edelsteine schön geformt, aus seiner Gnade durch das Wort.
Wenn wir uns lieben und vertrauen, (halleluja)
dann wächst der Tempel mehr und mehr...
</Text>
  </Song>
  <Song id="s0030">
    <Number>30</Number>
    <Title>Deine Herrschaft ruf ich aus</Title>
    <Text>Deine Herrschaft ruf ich aus über mich und die dich lieben.
Deine Herrschaft ruf ich aus über uns, die vor dir stehn.
Deine Herrschaft ruf ich aus über mich und die dir dienen.
Deine Herrschaft ruf ich aus über dein Volk!

Dass deine Schönheit wird gesehn, wo immer wir auch hingehn,
dass die Welt erkennt, du lebst und du regierst!   (2x)
</Text>
  </Song>
  <Song id="s0031">
    <Number>31</Number>
    <Title>May the fragrance</Title>
    <Text>Herr, erfüll diesen Ort mit Wohlgeruch,			(3x)
(diesen Ort erfüll, o Herr)
der aufsteigt von der Gemeind', die lobt und preist vor dir, dem König.

Herr, lass deine Gemeinde leuchten;			(3x)
(deine Gemeinde leuchten)
deine Herrlichkeit erstrahl, wenn wir dich ehrn, anbetend vor dem Thron.

Jesu Schönheit erfüll mein Leben;				(3x)
(seine Schönheit erfülle mich)
all mein Denken, Sein und Tun sei Zeugnis für meine Anbetung.

May the fragrance of Jesus fill this place,		(3x)
(lovely fragrance of Jesus)
rising from the sacrifice of lives laid down in adoration.

May the glory of Jesus fill His church,			(3x)
(radiant glory of Jesus)
shining from our faces as we gaze in adoration.

May the beauty of Jesus fill my life.				(3x)
(perfect beauty of Jesus)
Fill my thoughts, my words, my deeds; my all I give in adoration.











</Text>
  </Song>
  <Song id="s0032">
    <Number>32</Number>
    <Title>Ja, ich lieb dich mit der Liebe</Title>
    <Text>Ja, ich lieb dich mit der Liebe meines Herrn,
ja, ich lieb dich mit der Liebe meines Herrn,
und ich sehe in dir die Güte meines Herrn,
ja, ich lieb dich mit der Liebe meines Herrn.
</Text>
  </Song>
  <Song id="s0033">
    <Number>33</Number>
    <Title>Bind uns zusammen, Herr</Title>
    <Text>Bind uns zusammen, Herr, bind uns zusammen mit Banden,
die niemand kann brechen. Bind uns zusammen, Herr,
bind uns zusammen, Herr, bind uns zusammen mit Liebe.
Es gibt nur einen Gott, es gibt nur einen Sohn,
es gibt nur einen Geist, darum singen wir ...
</Text>
  </Song>
  <Song id="s0034">
    <Number>34</Number>
    <Title>Vater, mach uns eins</Title>
    <Text>Vater, mach uns eins, Vater, mach uns eins, dass die Welt erkennt,
du hast den Sohn gesandt. Vater, mach uns eins.

Siehe, wie fein und wie lieblich ist's, wenn Brüder in Einheit zusammen
sind, denn dort hast du den Segen verheissen: Leben in Ewigkeit.
</Text>
  </Song>
  <Song id="s0035">
    <Number>35</Number>
    <Title>Wir sind Brüder</Title>
    <Text>Wir sind Brüder, wir sind Schwestern, und wir dienen einander gern.
Wir gehören zusammen in dem Dienste unsres Herrn.
</Text>
  </Song>
  <Song id="s0036">
    <Number>36</Number>
    <Title>Lasst uns zusammen gehen</Title>
    <Text>Lasst uns zusammen gehen, einig im Geiste!
Mit einer Stimme erheben wir den Namen des Herrn.
Wir gehören zu seinem Reich. Dieses ist unser Lied:
Ich bin dein für das Königreich, ich bin dein für das Königreich.
</Text>
  </Song>
  <Song id="s0037">
    <Number>37</Number>
    <Title>Wir lieben und verehren dich</Title>
    <Text>Wir lieben und verehren dich, Christus, unser König.

Und wir folgen dir zusammen, wir folgen dir zusammen,
und wir folgen dir zusammen, Christus, unser König.
Und wir geben dir die Ehre ...
Und wir geben unser Leben ... Christus, unserm König.
</Text>
  </Song>
  <Song id="s0038">
    <Number>38</Number>
    <Title>Sei verherrlicht</Title>
    <Text>Sei verherrlicht	durch meinen Mund, durch meinen Mund,
sei verherrlicht	durch meinen Mund, o Gott.
....	durch meinen Leib
....	durch unser Lied
....	in unserm Dorf
....	in unserm Land
</Text>
  </Song>
  <Song id="s0039">
    <Number>39</Number>
    <Title>Öffne mir die Augen</Title>
    <Text>Öffne mir die Augen, ich will Jesus sehen,
mich ausstrecken zu ihm und sagen: Ich lieb dich.
Öffne mir die Ohren und hilf mir zu hören.
Öffne das Herz mir, ich will dir gehören.
</Text>
  </Song>
  <Song id="s0040">
    <Number>40</Number>
    <Title>Kommt zu mir</Title>
    <Text>Kommt zu mir, die ihr mühselig und beladen seid.
Kommt zu mir, und ich gebe euch Ruh.
Nehmt mein Joch und lernet von mir, denn ich bin sanftmütig und
von Herzen demütig. So werdet ihr finden Ruhe für eure Seelen,
denn mein Joch ist sanft, und meine Bürde ist leicht.
</Text>
  </Song>
  <Song id="s0041">
    <Number>41</Number>
    <Title>Seid still und erkennt</Title>
    <Text>Seid still und erkennt, dass ich bin Gott.			(3x)

Ich bin der Herr, dein Gott, der dich heilt.		(3x)

"Ja, dir, o Herr, vertraue ich."					(3x)
</Text>
  </Song>
  <Song id="s0042">
    <Number>42</Number>
    <Title>Jesus Christus spricht: Kommet her</Title>
    <Text>Jesus Christus spricht: Kommet her zu mir alle,
die ihr mühselig und beladen seid.
Siehe, ich will euch erquicken, spricht der Herr.   (2x)
</Text>
  </Song>
  <Song id="s0043">
    <Number>43</Number>
    <Title>Wo zwei oder drei</Title>
    <Text>Wo zwei oder drei in meinem Namen versammelt sind,
da bin ich mitten unter ihnen.
</Text>
  </Song>
  <Song id="s0044">
    <Number>44</Number>
    <Title>Let us break</Title>
    <Text>Let us break bread together on our knees.   (2x)
When I fall down on my knees with my face to the rising sun,
o Lord, have mercy on me!

Let us drink wine together on our knees ...
Let us praise God together on our knees ...
</Text>
  </Song>
  <Song id="s0045">
    <Number>45</Number>
    <Title>Auf, ihr Dürstenden alle</Title>
    <Text>Auf, ihr Dürstenden alle, kommet her zum Wasser,
und die ihr kein Brot habt, kommet.   (2x)
Höret, so wird eure Seele leben.   (2x)
Suchet den Herrn, jetzt, da er sich finden lässt;
rufet den Herrn, jetzt, da er nahe ist.
</Text>
  </Song>
  <Song id="s0046">
    <Number>46</Number>
    <Title>Ihr werdet die Kraft</Title>
    <Text>Ihr werdet die Kraft des Heiligen Geistes,
des Heiligen Geistes empfangen
und werdet meine Zeugen sein,
und werdet meine Zeugen sein,
meine Zeugen, meine Zeugen sein.
</Text>
  </Song>
  <Song id="s0047">
    <Number>47</Number>
    <Title>Ich bin bei euch alle Tage</Title>
    <Text>Ich bin bei euch alle Tage bis ans Ende der Welt, alle Tage, alle Tage.
</Text>
  </Song>
  <Song id="s0048">
    <Number>48</Number>
    <Title>Fürchte dich nicht</Title>
    <Text>Fürchte dich nicht, denn du bist mein,	(3x)		ich habe dich erlöst.

Wer auf den Herrn im Glauben harrt,	(3x)		fährt auf mit neuer Kraft.

Selig aus Gnaden darfst du sein,		(3x)		die Gabe Gottes ist's.

Wer überwindet, freue sich,				(3x)		er soll mein Erbe sein.

Wer mein Wort hält, lebt ewiglich		(3x)		und siehet nicht den Tod.
</Text>
  </Song>
  <Song id="s0049">
    <Number>49</Number>
    <Title>Ja, Herr, du bist bei mir</Title>
    <Text>Ja, Herr, du bist bei mir, und dafür dank ich dir.
Ja, Herr, du bist da, halleluja.   (2x)

Herr, wenn der Wunsch in meinem Herzen sich still in deinen Willen legt,
dann fühle ich trotz aller Schmerzen, dass deine Liebe mich umgibt.

Du lässt mich in die Tiefe gehen, damit ich sehe, wie ich bin.
Doch, Herr, du lässt mich nicht dort stehen, du ziehst mich
wieder zu dir hin.

Und wenn im eignen Woll'n und Ringen oft meine Hand ins Leere fasst -
du wirst mich doch nach Hause bringen, weil du mich angenommen hast.
</Text>
  </Song>
  <Song id="s0050">
    <Number>50</Number>
    <Title>Der Herr, mein Hirte</Title>
    <Text>Der Herr, mein Hirte, führet mich. Fürwahr, nichts mangelt mir.
Er lagert mich auf grünen Au'n bei frischem Wasser hier.

Erquickung schenkt er meiner Seel und führet gnädiglich
um seines hohen Namens Ehr auf rechter Strasse mich.

Geh ich durchs dunkle Todestal, ich fürcht kein Unglück dort.
Denn du bist da. Dein Stecken und Stab sind Tröstung mir und Hort.

Den Tisch bereitest du vor mir, selbst vor der Feinde Schar.
Mein Haupt salbst du mit deinem Oel. Mein Kelch fliesst über gar.

Ja, deine Güte folget mir, mein ganzes Leben lang.
Und immerdar, im Hause des Herrn, ertönt mein Lobgesang.



</Text>
  </Song>
  <Song id="s0051">
    <Number>51</Number>
    <Title>Wir singen von Jesus</Title>
    <Text>Wir singen von Jesus, sein ist Gewalt und Macht, er hat auf Golgatha
das Heil der Welt vollbracht. Der grosse Gott ist er und aller Herren Herr;
wir singen von Jesus mehr und mehr.

Wir singen von Jesus, er ist der gute Hirt, er sucht in Dunkelheit das Schaf,
das sich verirrt; strahlt selbst als Stern so hell, weist dir den Weg so schnell
heraus aus Sünde, Furcht und Höll.

Wir singen von Jesus, er ist das Lebensbrot, stillt Hunger in der Welt,
tröstet dich in der Not. Er trägt die Herrschaftskron, regiert vom
Himmelsthron, reicht Lebenswasser dir zum Lohn.

Wir singen von Jesus, er ist der starke Fels, er ist das Sündenlamm,
geschlachtet für die Welt; er ist der Bräutigam, zünd't ihm die Lichter an,
damit die Welt ihn sehen kann!
</Text>
  </Song>
  <Song id="s0052">
    <Number>52</Number>
    <Title>Siehe, in meine Hände</Title>
    <Text>Siehe, in meine Hände hab ich dich gezeichnet, spricht der Herr.   (2x)

Ich will vor dir hergehn und deine Wege ebnen,
sprenge Eisenriegel und breche starke Pforten.

Gehst du durch das Wasser, es wird dich nicht ertränken,
und selbst durch das Feuer will ich dich sicher leiten.

Mitten in der Wüste lass ich das Wasser quellen,
und durch dürre Täler führ ich die Wasserbäche.

Männer werden müde und Krieger müssen fallen.
Doch die Kraft des Herrn wird dich stets neu beflügeln.
</Text>
  </Song>
  <Song id="s0053">
    <Number>53</Number>
    <Title>Gott hat verheissen</Title>
    <Text>Gott hat verheissen, dass er wird ausgiessen
den Geist seiner Freude über uns.   (2x)
Freude inmitten der Not und der Schmerzen und Freude,
die sieget in Dunkelheit. Freude im Dienst, der verbunden
mit Tränen, ja Freude, die uns macht bereit.

Gott hat verheissen, dass er wird ausgiessen
den Geist des Gebetes über uns.   (2x)
Lasst uns anbeten im Geist und in Wahrheit den Vater,
den Sohn und den Heilgen Geist, denn er, der Heilge,
er sucht die Anbeter, die ihm allein geben die Ehr.

Gott hat verheissen, dass er wird ausgiessen
den Geist seiner Liebe über uns.   (2x)
Liebe, die hindrängt zum Bruder, zur Schwester, sie achtet
und ihnen in Stille dient. Liebe, die mutig zum Hoffen
und Leiden, die schnell und von Herzen vergibt.

Lasset uns warten und glaubensvoll hoffen,
dass Gott sein Versprechen selbst erfüllt.   (2x)
Ihn nicht durch Kleinglauben hindern und schmähen,
denn was er verheissen, geschieht; ihn nicht durch Kleinglauben
hindern und schmähen, denn was er versprochen, geschieht.










</Text>
  </Song>
  <Song id="s0054">
    <Number>54</Number>
    <Title>Hier bin ich vor dir</Title>
    <Text>Herr, füll mich neu, füll mich neu mit deinem Geiste,
der mich belebt und zu dir, mein Gott, hinziehet.

Hier bin ich vor dir. Leer sind meine Hände,
Herr, füll mich ganz mit dir!

Herr, füll mich neu, füll mich neu mit deiner Liebe,
die bei dir bleibt und mit Freuden Lasten träget.

Herr, füll mich neu, füll mich neu mit deinem Glauben,
der auf dich schaut und in andern Glauben wecket.

Herr, füll mich neu, füll mich neu mit deiner Freude,
die überströmt und in Lob und Preis dich rühmet.




</Text>
  </Song>
  <Song id="s0055">
    <Number>55</Number>
    <Title>Lass die Worte meines Mundes</Title>
    <Text>Lass die Worte meines Mundes und das Sinnen
meines Herzens wohlgefällig sein vor dir, o Herr.
O Herr, meine Stärke; o Herr, mein Leben.
</Text>
  </Song>
  <Song id="s0056">
    <Number>56</Number>
    <Title>Nimm du mich ganz hin</Title>
    <Text>Nimm du mich ganz hin, o Gottessohn. Du bist der Töpfer,
ich bin der Ton. Mach aus mir etwas nach deinem Sinn,
während ich harre, nimm mich ganz hin.

Nimm du mich ganz hin, o Gottessohn. Prüfe, erforsch mich
am Gnadenthron. Weisser denn Schnee, Herr, wasche mich rein,
dass ich dein eigen immer mag sein.

Nimm du mich ganz hin, o Gottessohn. Mit deinem Geiste
jetzt in mir wohn. Sei mir im Herzen König allein.
Lass alle sehen, dass ich ganz dein.




</Text>
  </Song>
  <Song id="s0057">
    <Number>57</Number>
    <Title>Herr, mach mich zum Werkzeug</Title>
    <Text>Herr, mach mich zum Werkzeug, zum Werkzeug der Liebe,
ich hebe die Hände zu dir.	(2x)

Ich sing dir aus Liebe ein Lied der Anbetung,
ich hebe die Hände zu dir.	(2x)

Herr, mach uns zur Einheit, zur Einheit in Liebe,
wir heben die Hände zu dir.	(2x)

Ich singe ein Liebeslied, ein Liebeslied für Jesus,
ich hebe die Hände zu dir.	(2x)

Fais de moi un instrument, un instrument d'adoration.
Je lève mes mains en ton nom.	(2x)

Fais de nous une symphonie, une symphonie d'adoration.
Nous levons nos mains en ton nom.	(2x)

Je te chanterai toujours, un chant d'amour, d'adoration.
Je lève mes mains en ton nom.	(2x)








</Text>
  </Song>
  <Song id="s0058">
    <Number>58</Number>
    <Title>Oh oui, je crois</Title>
    <Text>Oh oui, je crois.   (4x)
Je crois que c'est la vérité qui peut libérer!

Oh oui, je crois, (oh oui, je crois)   (2x)
car tous ce qu'il a promis est pour nous aujourd'hui.
</Text>
  </Song>
  <Song id="s0059">
    <Number>59</Number>
    <Title>Durchflute mein Herz</Title>
    <Text>Durchflute mein Herz, durchflute mein Herz,
Geist Gottes, durchflute mein Herz.
In dir hab ich Ruh, mein alles bist du,
Geist Gottes, durchflute mein Herz.
</Text>
  </Song>
  <Song id="s0060">
    <Number>60</Number>
    <Title>Herr, mein ganzes Leben</Title>
    <Text>Herr, mein ganzes Leben soll dir Ehre geben. Gib dazu Segen.

Father I adore You, lay my life before You. Oh, how I love You.

Jesus ...

Spirit ...
</Text>
  </Song>
  <Song id="s0061">
    <Number>61</Number>
    <Title>It’s the presence of Your spirit</Title>
    <Text>It's the presence of Your spirit, Lord we need.
So help us now to worship You.
It's the presence of Your spirit, Lord we need.

It's the presence of Your spirit, Lord we love ...

For the glowing of Your spirit, Lord we pray ...

For the presence of Your spirit, Lord we thank ...
</Text>
  </Song>
  <Song id="s0062">
    <Number>62</Number>
    <Title>Jesus, Jesus, let me tell You</Title>
    <Text>Jesus, Jesus, let me tell You how I feel:
You have given me Your spirit and I love You so.

Jesus, Jesus, du bist jeden Tag bei mir;
hast mir deinen Geist gegeben, und ich danke dir.
</Text>
  </Song>
  <Song id="s0063">
    <Number>63</Number>
    <Title>Du bisch Herr ... vo mim Läbe</Title>
    <Text>Du bisch Herr, du bisch Herr, du bisch Herr vo mim Läbe,
nimm du mich, bruch du mich, mach du mich doch zum Säge.
Jede Tag, jedi Schtund, lass du mich doch es Liecht für dich sii.
</Text>
  </Song>
  <Song id="s0064">
    <Number>64</Number>
    <Title>Du bist würdig, o so würdig</Title>
    <Text>Du bist würdig, o so würdig, und ich preise dich! Du bist würdig, o mein
Jesus, ich neige mich vor dir; du bist würdig der Anbetung, und ich bet
dich an. Ich preise dich und neig mich vor dir; ich bete, Herr dich an.

Du bist würdig, o so würdig, und ich ehre dich. Du bist würdig, o mein
Jesus, und ich glaub an dich. Du bist würdig des Vertrauens, ich
vertraue dir. Ich ehre dich, und ich glaub an dich; Herr, ich vertraue dir!

Du bist würdig, o so würdig, und ich liebe dich. Du bist würdig, o mein
Jesus, und ich diene dir. Du bist würdig meines Lebens, und ich geb mein
Leben dir. Ich liebe dich, und ich diene dir, mein Leben geb ich dir!
</Text>
  </Song>
  <Song id="s0065">
    <Number>65</Number>
    <Title>O mein Gott, ich trau</Title>
    <Text>Herr, zu dir erheb ich mich, um dich zu preisen.	(2x)

O mein Gott, ich trau auf dich: Lass mich nicht zuschanden sein,
dass meine Feinde nicht siegen über mich.

Wer auf dich vertraut, den wirst du nicht enttäuschen.	(2x)

Zeige mir, o Herr, deine Pfade und Wege.	(2x)

Denke nicht mehr, Herr, an die Sünden meiner Jugend.	(2x)

Gottes Wege sind: Güte, Treue und Wahrheit.	(2x)
</Text>
  </Song>
  <Song id="s0066">
    <Number>66</Number>
    <Title>Ich trau auf dich</Title>
    <Text>Ich trau auf dich, o Herr. Ich sage: Du bist mein Gott.
In deiner Hand steht meine Zeit, in deiner Hand steht meine Zeit.

Gelobet sei der Herr, denn er hat wunderbar
seine Liebe mir erwiesen und Güte mir gezeigt.
</Text>
  </Song>
  <Song id="s0067">
    <Number>67</Number>
    <Title>Das Höchste meines Lebens</Title>
    <Text>Das Höchste meines Lebens ist: Dich kennen, Herr!   (2x)
Dich kennen mehr und mehr, dich kennen mehr und mehr.
Das Höchste meines Lebens ist: Dich kennen, Herr!

Das Höchste meines Lebens ist: Dich lieben, Herr!

Das Höchste meines Lebens ist: Dir dienen, Herr!
</Text>
  </Song>
  <Song id="s0068">
    <Number>68</Number>
    <Title>You are the God that healeth me</Title>
    <Text>You are the God that healeth me, You are the Lord, my Healer.
You sent Your word and healed my disease, You are the Lord, my Healer!

Du bist mein Gott, der mich befreit, du bist der Herr, mein Heiler.
Du hast die Macht, zu heilen durch dein Wort!
Du bist der Herr, mein Heiler!
</Text>
  </Song>
  <Song id="s0069">
    <Number>69</Number>
    <Title>Lobe den Herrn, meine Seele</Title>
    <Text>Lobe den Herrn, meine Seele, und was in mir ist, seinen heilgen Namen.
Lobe den Herrn, meine Seele, und vergiss nicht, was er dir Gutes getan.
Der dir alle deine Sünden vergibt und heilet alle deine Gebrechen,
der dein Leben vom Verderben erlöst,
der dich krönt mit Gnade und  Barmherzigkeit,